### ISSUE TITLE
Implement push notification service via Google App Engine

### ISSUE THREAD

**Issue by tenmalin** [SafeSlingerProject/SafeSlinger-AppEngine#10]
See https://github.com/SafeSlingerProject/SafeSlinger-iOS/issues/55.

**Comment by mwfarb** [comment]
Duplicate of https://github.com/SafeSlingerProject/SafeSlinger-AppEngine/issues/4

**Comment by tenmalin** [comment]
Create branch https://github.com/SafeSlingerProject/SafeSlinger-AppEngine/tree/master for development.

**Comment by tenmalin** [comment]
Close at https://github.com/SafeSlingerProject/SafeSlinger-AppEngine/commit/067e5beac4462b98b338b09dfab961da50d2515b.
