### ISSUE TITLE
Migrate GAE python language support to newest version

### ISSUE THREAD

**Issue by tenmalin** [SafeSlingerProject/SafeSlinger-AppEngine#11]
In order to support SSL socket for APNS push notifications and prevent future deprecation on python 2.5, we have to migrate our servers to support python 2.7.

**Comment by tenmalin** [comment]
See https://github.com/SafeSlingerProject/SafeSlinger-AppEngine/issues/4 for detail about APNS mechanism.

**Comment by mwfarb** [comment]
Issue https://github.com/SafeSlingerProject/SafeSlinger-AppEngine/issues/3 mentions key excahnge, but it should be done for messaging as well.

**Comment by mwfarb** [comment]
Ready now and uploaded to production.
