### ISSUE TITLE
message longevity on the server

### ISSUE THREAD

**Issue by tenmalin** [SafeSlingerProject/SafeSlinger-AppEngine#16]
Some thoughts discussed with @mwfarb :
1. allow undownloaded message live longer.
2. remove messages in server storage if push notification is not succeed. 
3. user quota design for message storage (e.g.., 5 MB per device).
4. cron jobs for status check on all registered devices.

**Comment by tenmalin** [comment]
issues related to 4 are listed in https://github.com/SafeSlingerProject/SafeSlinger-AppEngine/issues/13 and https://github.com/SafeSlingerProject/SafeSlinger-AppEngine/issues/12.

**Comment by mwfarb** [comment]
Issues 1 and 2 resolved in https://github.com/SafeSlingerProject/SafeSlinger-AppEngine/commit/b3964e58921e4fee88d85da8fc18eca9681d858f.

**Comment by mwfarb** [comment]
Issue 4 resolved in 7cb7e5a.
