### ISSUE TITLE
add server side GCM support

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-AppEngine#17]
A long time coming:
https://developer.android.com/google/gcm/server.html

**Comment by tenmalin** [comment]
For @mwfarb , what is the exact part we need from 3rd party support? It seems like a similar issue we had before from urban airship.

**Comment by mwfarb** [comment]
Given our current model it should be the HTTP model outlined in the link, not XMPP. We should be able to connect to GCM servers directly, just as with C2DM. Am I missing something else you're referring too?

**Comment by mwfarb** [comment]
Complete now in 61b1b3ceba2ffbe6040f1ee278e266ea16f28d30
