### ISSUE TITLE
add additional CORS field on responses back to javascript client

### ISSUE THREAD

**Issue by tenmalin** [SafeSlingerProject/SafeSlinger-AppEngine#8]
Javascript clients cannot access the data receiving from the google app engine because "Access-Control-Allow-Origin" is not defined in all responses coming from the server.

Todo: Add "Access-Control-Allow-Origin: *"
See below:
http://enable-cors.org/server_appengine.html
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by mwfarb** [comment]
Committed and deployed at slinger-dev.
